# Generated by Django 5.2.7 on 2025-11-29 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('case', '0001_initial'),
        ('client', '0001_initial'),
        ('timeslot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Scheduled', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='case.case')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client.client')),
                ('timeslot', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='timeslot.timeslot')),
            ],
        ),
    ]
