# Generated by Django 5.2.7 on 2025-11-29 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        ('speciality', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('status', models.CharField(default='Open', max_length=20)),
                ('case_notes', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client.client')),
                ('speciality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='speciality.speciality')),
            ],
        ),
    ]
