# Generated by Django 5.2.7 on 2025-11-29 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lawyer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('is_booked', models.BooleanField(default=False)),
                ('lawyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lawyer.lawyer')),
            ],
        ),
    ]
