# Generated by Django 5.2.7 on 2025-12-01 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeslot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeslot',
            old_name='is_booked',
            new_name='booked',
        ),
    ]
