# Generated by Django 5.2.7 on 2025-12-01 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeslot', '0002_rename_is_booked_timeslot_booked'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='date',
            field=models.DateField(default='2025-12-01'),
            preserve_default=False,
        ),
    ]
